
export default {
    step: 1,
    // currentStep : 'UserLogin',
    adminEmail: '',
    adminPassword: '',
    adminAuthToken: '',
    companyName: '',
    companyWebsite: '',
    companyIndustryType: '',
    companyBio: '',
    userEmail: '',
    userPassword: '',
    userName: '',
    userFirstname: '',
    userLastname: '',
    userCountry: '',
    userAddress: '',
    userPhone: '',
    userDob: '',
    userType: '',
    clientName: '',
    clientEmail: '',
    clientPhone: '',
    clientBio: '',
    campaignName: '',
    campaignTitle: '',
    campaignDescription: '',
    campaignStartDate: '',
    campaignEndDate: '',
    campaignStatus: '',
    campaignclientId: ''

}
